# Generated by Django 3.0.5 on 2020-05-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('pass_word', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.classes')),
                ('teacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.classes')),
            ],
        ),
    ]
