# Generated by Django 3.0.5 on 2020-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='classID',
        ),
        migrations.RemoveField(
            model_name='teacher_class',
            name='classID',
        ),
        migrations.RemoveField(
            model_name='teacher_class',
            name='teacherID',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='alias_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='classes',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='teacher_class',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
    ]
